
var spelllist=new Array(
new Array('Aboleth', 'Huge Aberration', 'Aquatic', '07', 'Underground', '�', 'monstersA.html#aboleth', ' Aquatic subtype, darkvision 60 ft., mucus cloud'),
new Array('Achaierai', 'Large Outsider', 'Evil, Extraplanar, Lawful', '05', 'Lawful Plane', '�', 'monstersA.html#achaierai', ' Darkvision 60 ft., spell resistance 19'),
new Array('Air Elemental, Elder', 'Huge Elemental', 'Air, Extraplanar', '11', 'Plane of Air', '�', 'monstersEtoF.html#air-elemental', ' Damage reduction 10/�, darkvision 60 ft., elemental traits'),
new Array('Air Elemental, Greater', 'Huge Elemental', 'Air, Extraplanar', '09', 'Plane of Air', '�', 'monstersEtoF.html#air-elemental', ' Damage reduction 10/�, darkvision 60 ft., elemental traits'),
new Array('Air Elemental, Huge', 'Huge Elemental', 'Air, Extraplanar', '07', 'Plane of Air', '�', 'monstersEtoF.html#air-elemental', ' Damage reduction 5/�, darkvision 60 ft., elemental traits'),
new Array('Air Elemental, Large', 'Large Elemental', 'Air, Extraplanar', '05', 'Plane of Air', '�', 'monstersEtoF.html#air-elemental', ' Damage reduction 5/�, darkvision 60 ft., elemental traits'),
new Array('Air Elemental, Medium', 'Medium Elemental', 'Air, Extraplanar', '03', 'Plane of Air', '�', 'monstersEtoF.html#air-alemental', ' Darkvision 60 ft., elemental traits'),
new Array('Air Elemental, Small', 'Small Elemental', 'Air, Extraplanar', '01', 'Plane of Air', '�', 'monstersEtoF.html#air-elemental', ' Darkvision 60 ft., elemental traits'),
new Array('Allip', 'Medium Undead', 'Incorporeal', '03', 'Any', '�', 'monstersA.html#allip', ' Darkvision 60 ft., incorporeal traits, +2 turn resistance, undead traits'),
new Array('Angel, Astral Deva', 'Medium Outsider', 'Angel, Extraplanar, Good', '14', 'Good Plane', '+8', 'monstersA.html#astral-deva-angel', ' Damage reduction 10/evil, darkvision 60 ft., low-light vision, immunity to acid, cold, and petrification, protective aura, resistance to electricity 10 and fire 10, spell resistance 30, tongues, uncanny dodge'),
new Array('Angel, Planetar', 'Large Outsider', 'Angel, Extraplanar, Good', '16', 'Good Plane', '�', 'monstersA.html#planetar-angel', ' Damage reduction 10/evil, darkvision 60 ft., low-light vision, immunity to acid, cold, and petrification, protective aura, regeneration 10, resistance to electricity 10 and fire 10, spell resistance 30, tongues'),
new Array('Angel, Solar', 'Large Outsider', 'Angel, Extraplanar, Good', '23', 'Good Plane', '�', 'monstersA.html#solar-angel', ' Damage reduction 15/epic and evil, darkvision 60 ft., low-light vision, immunity to acid, cold, and petrification, protective aura, regeneration 15, resistance to electricity 10 and fire 10, spell resistance 32, tongues'),
new Array('Animated Object, Colossal', 'Colossal Construct', '', '10', 'Any', '�', 'monstersA.html#animated-object', ' Construct traits, darkvision 60 ft., low-light vision; also see text'),
new Array('Animated Object, Gargantuan', 'Gargantuan Construct', '', '07', 'Any', '�', 'monstersA.html#animated-object', ' Construct traits, darkvision 60 ft., low-light vision; also see text'),
new Array('Animated Object, Huge', 'Huge Construct', '', '05', 'Any', '�', 'monstersA.html#animated-object', ' Construct traits, darkvision 60 ft., low-light vision; also see text'),
new Array('Animated Object, Large', 'Large Construct', '', '03', 'Any', '�', 'monstersA.html#animated-object', ' Construct traits, darkvision 60 ft., low-light vision; also see text'),
new Array('Animated Object, Medium', 'Medium Construct', '', '02', 'Any', '�', 'monstersA.html#animated-object', ' Construct traits, darkvision 60 ft., low-light vision; also see text'),
new Array('Animated Object, Small', 'Small Construct', '', '01', 'Any', '�', 'monstersA.html#animated-object', ' Construct traits, darkvision 60 ft., low-light vision; also see text'),
new Array('Animated Object, Tiny', 'Tiny Construct', '', '1/2', 'Any', '�', 'monstersA.html#animated-object', ' Construct traits, darkvision 60 ft., low-light vision; also see text'),
new Array('Ankheg', 'Large Magical Beast', '', '03', 'Warm plains', '�', 'monstersA.html#ankheg', ' Darkvision 60 ft., low-light vision, tremorsense 60 ft.'),
new Array('Aranea', 'Medium Magical Beast', 'Shapechanger', '04', 'Temperate forests', '+4', 'monstersA.html#aranea', ' Change shape, darkvision 60 ft., low-light vision'),
new Array('Archon, Hound', 'Medium Outsider', 'Archon, Extraplanar, Good, Lawful', '04', 'Lawful Good Plane', '+5', 'monstersA.html#hound-archon', ' Aura of menace, change shape, damage reduction 10/evil, darkvision 60 ft., immunity to electricity and petrification, magic circle against evil, scent, spell resistance 16, teleport, tongues'),
new Array('Archon, Lantern', 'Small Outsider', 'Archon, Extraplanar, Good, Lawful', '02', 'Lawful Good Plane', '�', 'monstersA.html#lantern-archon', ' Aura of menace, damage reduction 10/evil and magic, darkvision 60 ft., immunity to electricity and petrification, magic circle against evil, teleport, tongues'),
new Array('Archon, Trumpet', 'Medium Outsider', 'Archon, Extraplanar, Good, Lawful', '14', 'Lawful Good Plane', '+8', 'monstersA.html#trumpet-archon', ' Aura of menace, damage reduction 10/evil, darkvision 60 ft., immunity to electricity and petrification, magic circle against evil, spell resistance 29, teleport, tongues'),
new Array('Arrowhawk, Adult', 'Medium Outsider', 'Air, Extraplanar', '05', 'Plane of Air', '�', 'monstersA.html#arrowhawk', ' Darkvision 60 ft., immunity to acid, electricity, and poison, resistance to cold 10 and fire 10'),
new Array('Arrowhawk, Elder', 'Large Outsider', 'Air, Extraplanar', '08', 'Plane of Air', '�', 'monstersA.html#arrowhawk', ' Darkvision 60 ft., immunity to acid, electricity, and poison, resistance to cold 10 and fire 10'),
new Array('Arrowhawk, Juvenile', 'Small Outsider', 'Air, Extraplanar', '03', 'Plane of Air', '�', 'monstersA.html#arrowhawk', ' Darkvision 60 ft., immunity to acid, electricity, and poison, resistance to cold 10 and fire 10'),
new Array('Assassin Vine', 'Large Plant', '', '03', 'Temperate forests', '�', 'monstersA.html#assassin-vine', ' Blindsight 30 ft., camouflage, immunity to electricity, low-light vision, plant traits, resistance to cold 10 and fire 10'),
new Array('Athach', 'Huge Aberration', '', '08', 'Temperate hills', '+5', 'monstersA.html#athach', ' Darkvision 60 ft.'),
new Array('Avoral', 'Medium Outsider', 'Extraplanar, Good', '09', 'Good Plane', '�', 'monstersA.html#avoral', ' Damage reduction 10/evil or silver, darkvision 60 ft., immunity to electricity and petrification, lay on hands, low-light vision, resistance to cold 10 and sonic 10, speak with animals, spell resistance 25, true seeing'),
new Array('Azer', 'Medium Outsider', 'Extraplanar, Fire', '02', 'Plane of Fire', '+4', 'monstersA.html#azer', ' Darkvision 60 ft., immunity to fire, spell resistance 13, vulnerability to cold'),
new Array('Barghest', 'Medium Outsider', 'Evil, Extraplanar, Lawful, Shapechanger', '04', 'Evil Plane', '�', 'monstersBtoC.html#barghest', ' Change shape, damage reduction 5/magic, darkvision 60 ft., scent'),
new Array('Barghest, Greater', 'Large Outsider', 'Evil, Extraplanar, Lawful, Shapechanger', '05', 'Evil Plane', '�', 'monstersBtoC.html#barghest', ' Change shape, damage reduction 10/magic, darkvision 60 ft., scent'),
new Array('Basilisk', 'Medium Magical Beast', '', '05', 'Warm deserts', '�', 'monstersBtoC.html#basilisk', ' Darkvision 60 ft., low-light vision'),
new Array('Behir', 'Huge Magical Beast', '', '08', 'Warm hills', '�', 'monstersBtoC.html#behir', ' Can�t be tripped, darkvision 60 ft., immunity to electricity, low-light vision, scent'),
new Array('Belker', 'Large Elemental', 'Air, Extraplanar', '06', 'Plane of Air', '�', 'monstersBtoC.html#belker', ' Darkvision 60 ft., elemental traits, smoke form'),
new Array('Blink Dog', 'Medium Magical Beast', '', '02', 'Temperate plains', '+2 (cohort)', 'monstersBtoC.html#blink-dog', ' Blink, darkvision 60 ft., dimension door, low-light vision, scent'),
new Array('Bodak', 'Medium Undead', 'Extraplanar', '08', 'Chaotic Evil Plane', '�', 'monstersBtoC.html#bodak', ' Damage reduction 10/cold iron, darkvision 60 ft., immunity to electricity, resistance to acid 10 and fire 10, undead traits, vulnerability to sunlight'),
new Array('Bralani', 'Medium Outsider', 'Chaotic, Extraplanar, Good', '06', 'Chaotic Good Plane', '+6', 'monstersBtoC.html#bralani', ' Alternate form, damage reduction 10/cold iron or evil, darkvision 60 ft., immunity to electricity and petrification, low-light vision, resistance to cold 10 and fire 10, spell resistance 17, tongues'),
new Array('Bugbear', 'Medium Humanoid', 'Goblinoid', '02', 'Temperate mountains', '+1', 'monstersBtoC.html#bugbear', ' Darkvision 60 ft., scent'),
new Array('Bulette', 'Huge Magical Beast', '', '07', 'Temperate hills', '�', 'monstersBtoC.html#bulette', ' Darkvision 60 ft., lowlight vision, scent, tremorsense 60 ft.'),
new Array('Centaur', 'Large Monstrous Humanoid', '', '03', 'Temperate forests', '+2', 'monstersBtoC.html#centaur', ' Darkvision 60 ft.'),
new Array('Chaos Beast', 'Medium Outsider', 'Chaotic, Extraplanar', '07', 'Limbo', '�', 'monstersBtoC.html#chaos-beast', ' Darkvision 60 ft., immunity to critical hits and transformation, spell resistance 15'),
new Array('Chimera', 'Large Magical Beast', '', '07', 'Temperate hills', '+2 (cohort)', 'monstersBtoC.html#chimera', ' Darkvision 60 ft., low-light vision, scent'),
new Array('Choker', 'Small Aberration', '', '02', 'Underground', '�', 'monstersBtoC.html#choker', ' Darkvision 60 ft., quickness'),
new Array('Chuul', 'Large Aberration', 'Aquatic', '07', 'Temperate marshes', '�', 'monstersBtoC.html#chuul', ' Amphibious, darkvision 60 ft., immunity to poison'),
new Array('Cloaker', 'Large Aberration', '', '05', 'Underground', '�', 'monstersBtoC.html#cloaker', ' Darkvision 60 ft., shadow shift'),
new Array('Cockatrice', 'Small Magical Beast', '', '03', 'Temperate plains', '�', 'monstersBtoC.html#cockatrice', ' Darkvision 60 ft., low-light vision'),
new Array('Couatl', 'Large Outsider', 'Native', '10', 'Warm forests', '+7', 'monstersBtoC.html#couatl', ' Darkvision 60 ft., ethereal jaunt, telepathy 90 ft.'),
new Array('Darkmantle', 'Small Magical Beast', '', '01', 'Underground', '�', 'monstersDtoDe.html#darkmantle', ' Blindsight 90 ft.'),
new Array('Delver', 'Huge Aberration', '', '09', 'Underground', '�', 'monstersDtoDe.html#delver', ' Darkvision 60 ft., immunity to acid, stone shape, tremorsense 60 ft.'),
new Array('Demon, Babau', 'Medium Outsider', 'Chaotic, Extraplanar, Evil', '06', 'Chaotic Evil Plane', '�', 'monstersDtoDe.html#babau-demon', ' Damage reduction 10/cold iron or Good, darkvision 60 ft., immunity to electricity and poison, protective slime, resistance to acid 10, cold 10, and fire 10, spell resistance 14, telepathy 100 ft.'),
new Array('Demon, Balor', 'Large Outsider', 'Chaotic, Extraplanar, Evil', '20', 'Chaotic Evil Plane', '�', 'monstersDtoDe.html#balor-demon', ' Damage reduction 15/cold iron and Good, darkvision 60 ft., flaming body, immunity to electricity, fire, and poison, resistance to acid 10 and cold 10, spell resistance 28, telepathy 100 ft., true seeing'),
new Array('Demon, Bebilith', 'Huge Outsider', 'Chaotic, Extraplanar, Evil', '10', 'Chaotic Evil Plane', '�', 'monstersDtoDe.html#bebilith-demon', ' Damage reduction 10/Good, darkvision 60 ft., plane shift, scent, telepathy 100 ft.'),
new Array('Demon, Dretch', 'Small Outsider', 'Chaotic, Extraplanar, Evil', '02', 'Chaotic Evil Plane', '+2', 'monstersDtoDe.html#dretch-demon', ' Damage reduction 5/cold iron or Good, darkvision 60 ft., immunity to electricity and poison, resistance to acid 10, cold 10, and fire 10, telepathy 100 ft.'),
new Array('Demon, Glabrezu', 'Huge Outsider', 'Chaotic, Extraplanar, Evil', '13', 'Chaotic Evil Plane', '�', 'monstersDtoDe.html#glabrezu-demon', ' Damage reduction 10/Good, darkvision 60 ft., immunity to electricity and poison, resistance to acid 10, cold 10, and fire 10, spell resistance 21, telepathy 100 ft., true seeing'),
new Array('Demon, Hezrou', 'Large Outsider', 'Chaotic, Extraplanar, Evil', '11', 'Chaotic Evil Plane', '+9', 'monstersDtoDe.html#hezrou-demon', ' Damage reduction 10/Good, darkvision 60 ft., immunity to electricity and poison, resistance to acid 10, cold 10, and fire 10, spell resistance 19, telepathy 100 ft.'),
new Array('Demon, Marilith', 'Large Outsider', 'Chaotic, Extraplanar, Evil', '17', 'Chaotic Evil Plane', '�', 'monstersDtoDe.html#marilith-demon', ' Damage reduction 10/Good and cold iron, darkvision 60 ft., immunity to electricity and poison, resistance to acid 10, cold 10, and fire 10, spell resistance 25, telepathy 100 ft.'),
new Array('Demon, Nalfeshnee', 'Huge Outsider', 'Chaotic, Extraplanar, Evil', '14', 'Chaotic Evil Plane', '�', 'monstersDtoDe.html#nalfeshnee-demon', ' Damage reduction 10/Good, darkvision 60 ft., immunity to electricity and poison, resistance to acid 10, cold 10, and fire 10, spell resistance 22, telepathy 100 ft., true seeing'),
new Array('Demon, Quasit', 'Tiny Outsider', 'Chaotic, Extraplanar, Evil', '02', 'Chaotic Evil Plane', '�', 'monstersDtoDe.html#quasit-demon', ' Alternate form, damage reduction 5/cold iron or Good, darkvision 60 ft., fast healing 2, immunity to poison, resistance to fire 10'),
new Array('Demon, Retriever', 'Huge Construct', 'Extraplanar', '11', 'Chaotic Evil Plane', '�', 'monstersDtoDe.html#retriever-demon', ' Construct traits, darkvision 60 ft., fast healing 5, low-light vision'),
new Array('Demon, Succubus', 'Medium Outsider', 'Chaotic, Extraplanar, Evil', '07', 'Chaotic Evil Plane', '+6', 'monstersDtoDe.html#succubus-demon', ' Damage reduction 10/cold iron or Good, darkvision 60 ft., immunity to electricity and poison, resistance to acid 10, cold 10, and fire 10, spell resistance 18, telepathy 100 ft., tongues'),
new Array('Demon, Vrock', 'Large Outsider', 'Chaotic, Extraplanar, Evil', '09', 'Chaotic Evil Plane', '+8', 'monstersDtoDe.html#vrock-demon', ' Damage reduction 10/Good, darkvision 60 ft., immunity to electricity and poison, resistance to acid 10, cold 10, and fire 10, spell resistance 17, telepathy 100 ft.'),
new Array('Derro', 'Small Monstrous Humanoid', '', '03', 'Underground', '� (+2 if sane)', 'monstersDtoDe.html#derro', ' Madness, spell resistance 15 vulnerability to sunlight'),
new Array('Destrachan', 'Large Aberration', '', '08', 'Underground', '�', 'monstersDtoDe.html#destrachan', ' Blindsight 100 ft., immunities, protection from sonics'),
new Array('Devil, Barbed (Hamatula)', 'Medium Outsider', 'Evil, Extraplanar, Lawful', '11', 'Lawful Evil Plane', '�', 'monstersDtoDe.html#barbed-devil', ' Barbed defense, damage reduction 10/Good, darkvision 60 ft., immunity to fire and poison, resistance to acid 10 and cold 10, see in darkness, spell resistance 23, spell-like abilities, telepathy 100 ft.'),
new Array('Devil, Bearded (Barbazu)', 'Medium Outsider', 'Evil, Extraplanar, Lawful', '05', 'Lawful Evil Plane', '+6', 'monstersDtoDe.html#bearded-devil', ' Damage reduction 5/silver or Good, darkvision 60 ft., immunity to fire and poison, resistance to acid 10 and cold 10, see in darkness, spell resistance 17, telepathy 100 ft.'),
new Array('Devil, Bone (Osyluth)', 'Large Outsider', 'Evil, Extraplanar, Lawful', '09', 'Lawful Evil Plane', '�', 'monstersDtoDe.html#bone-devil', ' Damage reduction 10/Good, darkvision 60 ft., immunity to fire and poison, resistance to acid 10 and cold 10, see in darkness, spell resistance 21, telepathy 100 ft.'),
new Array('Devil, Chain (Kyton)', 'Medium Outsider', 'Evil, Extraplanar, Lawful', '06', 'Lawful Evil Plane', '+6', 'monstersDtoDe.html#chain-devil', ' Damage reduction 5/silver or Good, darkvision 60 ft., immunity to cold, regeneration 2, spell resistance 18'),
new Array('Devil, Erinyes', 'Medium Outsider', 'Evil, Extraplanar, Lawful', '08', 'Lawful Evil Plane', '+7', 'monstersDtoDe.html#erinyes-devil', ' Damage reduction 5/Good, darkvision 60 ft., immunity to fire and poison, resistance to acid 10 and cold 10, see in darkness, spell resistance 20, telepathy 100 ft., true seeing'),
new Array('Devil, Hellcat (Bezekira)', 'Large Outsider', 'Evil, Extraplanar, Lawful', '07', 'Lawful Evil Plane', '�', 'monstersDtoDe.html#hellcat-devil', ' Damage reduction 5/Good, darkvision 60 ft., invisible in light, resistance to fire 10, scent, spell resistance 19, telepathy 100 ft.'),
new Array('Devil, Horned (Cornugon)', 'Large Outsider', 'Evil, Extraplanar, Lawful', '16', 'Lawful Evil Plane', '�', 'monstersDtoDe.html#horned-devil', ' Damage reduction 10/Good and silver, darkvision 60 ft., immunity to fire and poison, resistance to acid 10 and cold 10, regeneration 5, see in darkness, spell resistance 28, telepathy 100 ft.'),
new Array('Devil, Ice (Gelugon)', 'Large Outsider', 'Evil, Extraplanar, Lawful', '13', 'Lawful Evil Plane', '�', 'monstersDtoDe.html#ice-devil', ' Damage reduction 10/Good, darkvision 60 ft., immunity to fire and poison, resistance to acid 10 and cold 10, regeneration 5, see in darkness, spell resistance 25, telepathy 100 ft.'),
new Array('Devil, Lemure', 'Medium Outsider', 'Evil, Extraplanar, Lawful', '01', 'Lawful Evil Plane', '�', 'monstersDtoDe.html#lemure-devil', ' Damage reduction 5/Good or silver, darkvision 60 ft., immunity to fire and poison, mindless, resistance to acid 10 and cold 10, mindless, see in darkness'),
new Array('Devil, Pit Fiend', 'Large Outsider', 'Evil, Extraplanar, Lawful', '20', 'Lawful Evil Plane', '�', 'monstersDtoDe.html#pit-fiend-devil', ' Damage reduction 15/Good and silver, darkvision 60 ft., immunity to fire and poison, resistance to acid 10 and cold 10, regeneration 5, see in darkness, spell resistance 32, telepathy 100 ft.'),
new Array('Devourer', 'Large Undead', 'Extraplanar', '11', 'Any', '�', 'monstersDtoDe.html#devourer', ' Darkvision 60 ft., spell deflection, spell resistance 21, undead traits'),
new Array('Digester', 'Medium Magical Beast', '', '06', 'Warm forests', '�', 'monstersDitoDo.html#digester', ' Darkvision 60 ft., immunity to acid, low-light vision, scent'),
new Array('Dinosaur, Deinonychus', 'Medium Animal', '', '03', 'Warm forests', '�', 'monstersDitoDo.html#deinonychus-dinosaur', ' Low-light vision, scent'),
new Array('Dinosaur, Elasmosaurus', 'Huge Animal', '', '07', 'Warm aquatic', '�', 'monstersDitoDo.html#elasmosaurus-dinosaur', ' Low-light vision, scent'),
new Array('Dinosaur, Megaraptor', 'Huge Animal', '', '06', 'Warm forests', '�', 'monstersDitoDo.html#megaraptor-dinosaur', ' Low-light vision, scent'),
new Array('Dinosaur, Triceratops', 'Huge Animal', '', '09', 'Temperate plains', '�', 'monstersDitoDo.html#triceratops-dinosaur', ' Low-light vision, scent'),
new Array('Dinosaur, Tyrannosaurus', 'Huge Animal', '', '08', 'Warm plains', '�', 'monstersDitoDo.html#tyrannosaurus-dinosaur', ' Low-light vision, scent'),
new Array('Dire Ape', 'Large Animal', '', '03', 'Warm forests', '�', 'monstersDitoDo.html#dire-ape', ' Low-light vision, scent'),
new Array('Dire Badger', 'Medium Animal', '', '02', 'Temperate forests', '�', 'monstersDitoDo.html#dire-badger', ' Low-light vision, scent'),
new Array('Dire Bat', 'Large Animal', '', '02', 'Temperate deserts', '�', 'monstersDitoDo.html#dire-bat', ' Blindsense 40 ft.'),
new Array('Dire Bear', 'Large Animal', '', '07', 'Cold forests', '�', 'monstersDitoDo.html#dire-bear', ' Low-light vision, scent'),
new Array('Dire Boar', 'Large Animal', '', '04', 'Temperate forests', '�', 'monstersDitoDo.html#dire-boar', ' Low-light vision, scent'),
new Array('Dire Lion', 'Large Animal', '', '05', 'Warm plains', '�', 'monstersDitoDo.html#dire-lion', ' Low-light vision, scent'),
new Array('Dire Rat', 'Small Animal', '', '1/2', 'Any', '�', 'monstersDitoDo.html#dire-rat', ' Low-light vision, scent'),
new Array('Dire Shark', 'Huge Animal', 'Aquatic', '09', 'Cold aquatic', '�', 'monstersDitoDo.html#dire-shark', ' Keen scent'),
new Array('Dire Tiger', 'Large Animal', '', '08', 'Warm forests', '�', 'monstersDitoDo.html#dire-tiger', ' Low-light vision, scent'),
new Array('Dire Weasel', 'Medium Animal', '', '02', 'Temperate hills', '�', 'monstersDitoDo.html#dire-weasel', ' Low-light vision, scent'),
new Array('Dire Wolf', 'Large Animal', '', '03', 'Temperate forests', '�', 'monstersDitoDo.html#dire-wolf', ' Low-light vision, scent'),
new Array('Dire Wolverine', 'Large Animal', '', '04', 'Cold forests', '�', 'monstersDitoDo.html#dire-wolverine', ' Low-light vision, scent'),
new Array('Doppelganger', 'Medium Monstrous Humanoid', 'Shapechanger', '03', 'Any', '+4', 'monstersDitoDo.html#doppelganger', ' Change shape, immunity to sleep and charm effects'),
new Array('Dragon Turtle', 'Huge Dragon', 'Aquatic', '09', 'Temperate aquatic', '�', 'monstersDrtoDw.html#dragon-turtle', ' Darkvision 60 ft., immunity to fire, sleep, and paralysis, low-light vision, scent'),
new Array('Dragonne', 'Large Magical Beast', '', '07', 'Temperate deserts', '+4 (cohort)', 'monstersDrtoDw.html#dragonne', ' Darkvision 60 ft., low-light vision, scent'),
new Array('Drider', 'Large Aberration', '', '07', 'Underground', '+4', 'monstersDrtoDw.html#drider', ' Darkvision 60 ft., spell resistance 17'),
new Array('Drow', 'Medium Humanoid', 'Elf ', '01', 'Underground', '+2', 'monstersDitoDo.html#drow', ' Drow traits, spell resistance 12'),
new Array('Dryad', 'Medium Fey', '', '03', 'Temperate forests', '�', 'monstersDrtoDw.html#dryad', ' Damage reduction 5/cold iron, tree dependent, wild empathy'),
new Array('Duergar', 'Medium Humanoid', 'Dwarf', '01', 'Underground', '+1', 'monstersDrtoDw.html#duergar', ' Darkvision 60 ft., duergar traits'),
new Array('Dwarf', 'Medium Humanoid', 'Dwarf', '1/2', 'Temperate mountains', '+0', 'monstersDrtoDw.html#dwarf', ' Darkvision 60 ft., dwarf traits'),
new Array('Eagle, Giant', 'Large Magical Beast', '', '03', 'Temperate mountains', '+2 (cohort)', 'monstersEtoF.html#giant-eagle', ' Low-light vision, evasion'),
new Array('Earth Elemental, Elder', 'Huge Elemental', 'Earth, Extraplanar', '11', 'Plane of Earth', '�', 'monstersEtoF.html#earth-elemental', ' Damage reduction 10/�, earth glide, darkvision 60 ft., elemental traits'),
new Array('Earth Elemental, Greater', 'Huge Elemental', 'Earth, Extraplanar', '09', 'Plane of Earth', '�', 'monstersEtoF.html#earth-elemental', ' Damage reduction 10/�, earth glide, darkvision 60 ft., elemental traits'),
new Array('Earth Elemental, Huge', 'Huge Elemental', 'Earth, Extraplanar', '07', 'Plane of Earth', '�', 'monstersEtoF.html#earth-elemental', ' Damage reduction 5/�, earth glide, darkvision 60 ft., elemental traits'),
new Array('Earth Elemental, Large', 'Large Elemental', 'Earth, Extraplanar', '05', 'Plane of Earth', '�', 'monstersEtoF.html#earth-elemental', ' Damage reduction 5/�, earth glide, darkvision 60 ft., elemental traits'),
new Array('Earth Elemental, Medium', 'Medium Elemental', 'Earth, Extraplanar', '03', 'Plane of Earth', '�', 'monstersEtoF.html#earth-elemental', ' Darkvision 60 ft., earth glide, elemental traits'),
new Array('Earth Elemental, Small', 'Small Elemental', 'Earth, Extraplanar', '01', 'Plane of Earth', '�', 'monstersEtoF.html#earth-elemental', ' Darkvision 60 ft., earth glide, elemental traits'),
new Array('Elf', 'Medium Humanoid', 'Elf ', '1/2', 'Temperate forest', '+0', 'monstersEtoF.html#elf', ' Elven traits'),
new Array('Ethereal Filcher', 'Medium Aberration', '', '03', 'Underground', '�', 'monstersEtoF.html#ethereal-filcher', ' Darkvision 60 ft., detect magic, ethereal jaunt'),
new Array('Ethereal Marauder', 'Medium Magical Beast', 'Extraplanar', '03', 'Ethereal Plane', '�', 'monstersEtoF.html#ethereal-marauder', ' Darkvision 60 ft., ethereal jaunt'),
new Array('Ettercap', 'Medium Aberration', '', '03', 'Warm forests', '+4', 'monstersEtoF.html#ettercap', ' Low-light vision'),
new Array('Ettin', 'Large Giant', '', '06', 'Cold hills', '+5', 'monstersEtoF.html#ettin', ' Low-light vision, superior two-weapon fighting'),
new Array('Fire Elemental, Elder', 'Huge Elemental', 'Fire, Extraplanar', '11', 'Plane of Fire', '�', 'monstersEtoF.html#fire-elemental', ' Damage reduction 10/�, darkvision 60 ft., elemental traits, immunity to fire, vulnerability to cold'),
new Array('Fire Elemental, Greater', 'Huge Elemental', 'Fire, Extraplanar', '09', 'Plane of Fire', '�', 'monstersEtoF.html#fire-elemental', ' Damage reduction 10/�, darkvision 60 ft., elemental traits, immunity to fire, vulnerability to cold'),
new Array('Fire Elemental, Huge', 'Huge Elemental', 'Fire, Extraplanar', '07', 'Plane of Fire', '�', 'monstersEtoF.html#fire-elemental', ' Damage reduction 5/�, darkvision 60 ft., elemental traits, immunity to fire, vulnerability to cold'),
new Array('Fire Elemental, Large', 'Large Elemental', 'Fire, Extraplanar', '05', 'Plane of Fire', '�', 'monstersEtoF.html#fire-elemental', ' Damage reduction 5/�, darkvision 60 ft., elemental traits, immunity to fire, vulnerability to cold'),
new Array('Fire Elemental, Medium', 'Medium Elemental', 'Fire, Extraplanar', '03', 'Plane of Fire', '�', 'monstersEtoF.html#fire-elemental', ' Darkvision 60 ft., elemental traits, immunity to fire, vulnerability to cold'),
new Array('Fire Elemental, Small', 'Small Elemental', 'Fire, Extraplanar', '01', 'Plane of Fire', '�', 'monstersEtoF.html#fire-elemental', ' Darkvision 60 ft., elemental traits, immunity to fire, vulnerability to cold'),
new Array('Formian Myrmarch', 'Large Outsider', '', '10', 'Lawful Plane', '�', 'monstersEtoF.html#formian', ' Fast healing 2, hive mind, immunity to poison, petrification, and cold, resistance to electricity 10, fire 10, and sonic 10, spell resistance 25'),
new Array('Formian Queen', 'Large Outsider', '', '17', 'Lawful Plane', '�', 'monstersEtoF.html#formian', ' Fast healing 2, hive mind, immunity to poison, petrification, and cold, resistance to electricity 10, fire 10, and sonic 10, spell resistance 30, telepathy'),
new Array('Formian Taskmaster', 'Medium Outsider', '', '07', 'Lawful Plane', '�', 'monstersEtoF.html#formian', ' Hive mind, immunity to poison, petrification, and cold, resistance to electricity 10, fire 10, and sonic 10, spell resistance 21, telepathy 100 ft.'),
new Array('Formian Warrior', 'Medium Outsider', '', '03', 'Lawful Plane', '�', 'monstersEtoF.html#formian', ' Hive mind, immunity to poison, petrification, and cold, resistance to electricity 10, fire 10, and sonic 10, spell resistance 18'),
new Array('Formian Worker', 'Small Outsider', 'Lawful, Extraplanar', '1/2', 'Lawful Plane', '�', 'monstersEtoF.html#formian', ' Cure serious wounds, hive mind, immunity to poison, petrification, and cold, make whole, resistance to electricity 10, fire 10, and sonic 10'),
new Array('Frost Worm', 'Huge Magical Beast', 'Cold', '12', 'Cold plains', '�', 'monstersEtoF.html#frost-worm', ' Darkvision 60 ft., death throes, immunity to cold, low-light vision, vulnerability to fire'),
new Array('Fungus, Shrieker', 'Medium Plant', '', '01', 'Underground', '�', 'monstersEtoF.html#fungus', ' Low-light vision, plant traits'),
new Array('Fungus, Violet', 'Medium Plant', '', '03', 'Underground', '�', 'monstersEtoF.html#fungus', ' Low-light vision, plant traits'),
new Array('Gargoyle', 'Medium Monstrous Humanoid', 'Earth', '04', 'Any', '+5', 'monstersG.html#gargoyle', ' Damage reduction 10/magic, darkvision 60 ft., freeze'),
new Array('Genie, Djinni', 'Large Outsider', 'Air, Extraplanar', '05', 'Plane of Air', '+6', 'monstersG.html#djinni', ' Darkvision 60 ft., immunity to acid, plane shift, telepathy 100 ft.'),
new Array('Genie, Efreeti', 'Large Outsider', 'Extraplanar, Fire', '08', 'Plane of Fire', '�', 'monstersG.html#efreeti', ' Darkvision 60 ft., immunity to fire, plane shift, telepathy 100 ft., vulnerability to cold'),
new Array('Genie, Janni', 'Medium Outsider', 'Native', '04', 'Warm deserts', '+5', 'monstersG.html#janni', ' Darkvision 60 ft., elemental endurance, plane shift, resistance to fire 10, telepathy 100 ft.'),
new Array('Ghaele', 'Medium Outsider', 'Chaotic, Extraplanar, Good', '13', 'Chaotic Good Plane', '�', 'monstersG.html#ghaele', ' Alternate form, damage reduction 10/evil and cold iron, darkvision 60 ft., immunity to electricity and petrification, lowlight vision, protective aura, resistance to cold 10 and fire 10 spell resistance 28, tongues'),
new Array('Ghast', 'Medium Undead', '', '03', 'Any', '�', 'monstersG.html#ghast', ' Darkvision 60 ft., undead traits, +2 turn resistance'),
new Array('Ghoul', 'Medium Undead', '', '01', 'Any', '�', 'monstersG.html#ghoul', ' Darkvision 60 ft., undead traits, +2 turn resistance'),
new Array('Giant, Cloud', 'Huge Giant', 'Air', '11', 'Temperate mountains', '�', 'monstersG.html#cloud-giant', ' Low-light vision, oversized weapon, rock catching, scent'),
new Array('Giant, Fire', 'Large Giant', 'Fire', '10', 'Warm mountains', '+4', 'monstersG.html#fire-giant', ' Immunity to fire, low-light vision, rock catching, vulnerability to cold'),
new Array('Giant, Frost', 'Large Giant', 'Cold', '09', 'Cold mountains', '+4', 'monstersG.html#frost-giant', ' Immunity to cold, low-light vision, rock catching, vulnerability to fire'),
new Array('Giant, Hill', 'Large Giant', '', '07', 'Temperate hills', '+4', 'monstersG.html#hill-giant', ' Low-light vision, rock catching'),
new Array('Giant, Stone', 'Large Giant', 'Earth', '08', 'Temperate mountains', '+4 (elder +6)', 'monstersG.html#stone-giant', ' Darkvision 60 ft., low-light vision, rock catching'),
new Array('Giant, Storm', 'Huge Giant', '', '13', 'Warm mountains', '�', 'monstersG.html#storm-giant', ' Freedom of movement, immunity to electricity, low-light vision, rock catching, water breathing'),
new Array('Gibbering Mouther', 'Medium Aberration', '', '05', 'Underground', '�', 'monstersG.html#gibbering-mouther', ' Amorphous, damage reduction 5/bludgeoning, darkvision 60 ft.'),
new Array('Girallon', 'Large Magical Beast', '', '06', 'Warm forests', '�', 'monstersG.html#girallon', ' Darkvision 60 ft., low-light vision, scent'),
new Array('Gnoll', 'Medium Humanoid', 'Gnoll', '01', 'Warm plains', '+1', 'monstersG.html#gnoll', ' Darkvision 60 ft.'),
new Array('Gnome', 'Small Humanoid', 'Gnome', '1/2', 'Temperate hills', '+0', 'monstersG.html#gnome', ' Gnome traits'),
new Array('Goblin', 'Small Humanoid', 'Goblinoid', '1/2', 'Temperate plains', '+0', 'monstersG.html#goblin', ' Darkvision 60 ft.'),
new Array('Golem, Clay', 'Large Construct', '', '10', 'Any', '�', 'monstersG.html#clay-golem', ' Construct traits, damage reduction 10/adamantine and bludgeoning, darkvision 60 ft., haste, immunity to magic, low-light vision'),
new Array('Golem, Flesh', 'Large Construct', '', '07', 'Any', '�', 'monstersG.html#flesh-golem', ' Construct traits, damage reduction 5/adamantine, darkvision 60 ft., immunity to magic, low-light vision'),
new Array('Golem, Iron', 'Large Construct', '', '13', 'Any', '�', 'monstersG.html#iron-golem', ' Construct traits, damage reduction 15/adamantine, darkvision 60 ft., immunity to magic, low-light vision'),
new Array('Golem, Stone', 'Large Construct', '', '11', 'Any', '�', 'monstersG.html#stone-golem', ' Construct traits, damage reduction 10/adamantine, darkvision 60 ft., immunity to magic, low-light vision'),
new Array('Gorgon', 'Large Magical Beast', '', '08', 'Temperate plains', '�', 'monstersG.html#gorgon', ' Darkvision 60 ft., lowlight vision, scent'),
new Array('Gray Render', 'Large Magical Beast', '', '08', 'Temperate marshes', '+5 (cohort)', 'monstersG.html#gray-render', ' Darkvision 60 ft., low-light vision, scent'),
new Array('Grick', 'Medium Aberration', '', '03', 'Underground', '�', 'monstersG.html#grick', ' Damage reduction 10/magic, darkvision 60 ft., scent'),
new Array('Griffon', 'Large Magical Beast', '', '04', 'Temperate hills', '+3 (cohort)', 'monstersG.html#griffon', ' Darkvision 60 ft., low-light vision, scent'),
new Array('Grimlock', 'Medium Monstrous Humanoid', '', '01', 'Underground', '+2', 'monstersG.html#grimlock', ' Blindsight 40 ft., immunities, scent'),
new Array('Hag, Annis', 'Large Monstrous Humanoid', '', '06', 'Cold marshes', '�', 'monstersHtoI.html#annis-hag', ' Damage reduction 2/bludgeoning, darkvision 60 ft., spell resistance 19'),
new Array('Hag, Green', 'Medium Monstrous Humanoid', '', '05', 'Temperate marshes', '�', 'monstersHtoI.html#green-hag', ' Darkvision 90 ft., spell resistance 18'),
new Array('Hag, Sea', 'Medium Monstrous Humanoid', 'Aquatic', '04', 'Temperate aquatic', '�', 'monstersHtoI.html#sea-hag', ' Amphibious, spell resistance 14'),
new Array('Halfling', 'Small Humanoid', 'Halfling', '1/2', 'Warm plains', '+0', 'monstersHtoI.html#halfling', ' Halfling traits'),
new Array('Harpy', 'Medium Monstrous Humanoid', '', '04', 'Temperate marshes', '+3', 'monstersHtoI.html#harpy', ' Darkvision 60 ft.'),
new Array('Hell Hound', 'Medium Outsider', 'Evil, Extraplanar, Fire, Lawful', '03', 'Lawful Evil Plane', '+3 (cohort)', 'monstersHtoI.html#hell-hound', ' Darkvision 60 ft., immunity to fire, scent, vulnerability to cold'),
new Array('Hippogriff', 'Large Magical Beast', '', '02', 'Temperate hills', '�', 'monstersHtoI.html#hippogriff', ' Darkvision 60 ft., low-light vision, scent'),
new Array('Hobgoblin', 'Medium Humanoid', 'Goblinoid', '1/2', 'Warm hills', '+1', 'monstersHtoI.html#hobgoblin', ' Darkvision 60 ft.'),
new Array('Homunculus', 'Tiny Construct', '', '01', 'Any', '�', 'monstersHtoI.html#homunculus', ' Construct traits, darkvision 60 ft., low-light vision'),
new Array('Howler', 'Large Outsider', 'Chaotic, Evil, Extraplanar', '03', 'Chaotic Plane', '+3 (cohort)', 'monstersHtoI.html#howler', ' Darkvision 60 ft.'),
new Array('Hydra, Eight-Headed', 'Huge Magical Beast', '', '07', 'Temperate marshes', '�', 'monstersHtoI.html#hydra', ' Darkvision 60 ft., fast healing 18, low-light vision, scent'),
new Array('Hydra, Eleven-Headed', 'Huge Magical Beast', '', '10', 'Temperate marshes', '�', 'monstersHtoI.html#hydra', ' Darkvision 60 ft., fast healing 21, low-light vision, scent'),
new Array('Hydra, Five-Headed', 'Huge Magical Beast', '', '04', 'Temperate marshes', '�', 'monstersHtoI.html#hydra', ' Darkvision 60 ft., fast healing 15, low-light vision, scent'),
new Array('Hydra, Nine-Headed', 'Huge Magical Beast', '', '08', 'Temperate marshes', '�', 'monstersHtoI.html#hydra', ' Darkvision 60 ft., fast healing 19, low-light vision, scent'),
new Array('Hydra, Seven-Headed', 'Huge Magical Beast', '', '06', 'Temperate marshes', '�', 'monstersHtoI.html#hydra', ' Darkvision 60 ft., fast healing 17, low-light vision, scent'),
new Array('Hydra, Six-Headed', 'Huge Magical Beast', '', '05', 'Temperate marshes', '�', 'monstersHtoI.html#hydra', ' Darkvision 60 ft., fast healing 16, low-light vision, scent'),
new Array('Hydra, Ten-Headed', 'Huge Magical Beast', '', '09', 'Temperate marshes', '�', 'monstersHtoI.html#hydra', ' Darkvision 60 ft., fast healing 20, low-light vision, scent'),
new Array('Hydra, Twelve-Headed', 'Huge Magical Beast', '', '11', 'Temperate marshes', '�', 'monstersHtoI.html#hydra', ' Darkvision 60 ft., fast healing 22, low-light vision, scent'),
new Array('Inevitable, Kolyarut', 'Medium Construct', 'Extraplanar, Lawful', '12', 'Lawful Plane', '�', 'monstersHtoI.html#kolyarut-inevitable', ' Construct traits, damage reduction 10/Chaotic, darkvision 60 ft., fast healing 5, low-light vision, spell resistance 22'),
new Array('Inevitable, Marut', 'Large Construct', 'Extraplanar, Lawful', '15', 'Lawful Plane', '�', 'monstersHtoI.html#marut-inevitable', ' Construct traits, damage reduction 15/Chaotic, darkvision 60 ft., fast healing 10, low-light vision, spell resistance 25'),
new Array('Inevitable, Zelekhut', 'Large Construct', 'Extraplanar, Lawful', '09', 'Lawful Plane', '+7', 'monstersHtoI.html#zelekhut-inevitable', ' Construct traits, damage reduction 10/Chaotic, darkvision 60 ft., fast healing 5, low-light vision, spell resistance 20'),
new Array('Invisible Stalker', 'Large Elemental', 'Air, Extraplanar', '07', 'Plane of Air', '�', 'monstersHtoI.html#invisible-stalker', ' Darkvision 60 ft., elemental traits, natural invisibility, improved tracking'),
new Array('Kobold', 'Small Humanoid', 'Reptilian', '1/2', 'Temperate forests', '+0', 'monstersKtoL.html#kobold', ' Darkvision 60 ft., light sensitivity'),
new Array('Kraken', 'Gargantuan Magical Beast', 'Aquatic', '12', 'Temperate aquatic', '�', 'monstersKtoL.html#kraken', ' Darkvision 60 ft., ink cloud, jet, low-light vision, spell-like abilities'),
new Array('Krenshar', 'Medium Magical Beast', '', '01', 'Temperate forests', '+2', 'monstersKtoL.html#krenshar', ' Darkvision 60 ft., low-light vision, scent'),
new Array('Lamia', 'Large Magical Beast', '', '06', 'Temperate deserts', '+4', 'monstersKtoL.html#lamia', ' Darkvision 60 ft., low-light vision'),
new Array('Lammasu', 'Large Magical Beast', '', '08', 'Temperate deserts', '+5', 'monstersKtoL.html#lammasu', ' Darkvision 60 ft., low-light vision, magic circle against evil, spell-like abilities'),
new Array('Leonal', 'Medium Outsider', 'Extraplanar, Good', '12', 'Good Plane', '�', 'monstersKtoL.html#leonal', ' Damage reduction 10/evil and silver, darkvision 60 ft., immunity to electricity and petrification, lay on hands, lowlight vision, protective aura, resistance to cold 10 and sonic 10, speak with animals, spell resistance 28'),
new Array('Lillend', 'Large Outsider', 'Chaotic, Extraplanar, Good', '07', 'Chaos Plane', '+6', 'monstersKtoL.html#lillend', ' Darkvision 60 ft., immunity to poison, resistance to fire 10'),
new Array('Lizardfolk', 'Medium Humanoid', 'Reptilian', '01', 'Temperate marshes', '+1', 'monstersKtoL.html#lizardfolk', ' 5 ft./5 ft.'),
new Array('Locathah', 'Medium Humanoid', 'Aquatic', '1/2', 'Warm aquatic', '+1', 'monstersKtoL.html#locathah', ' �'),
new Array('Magmin', 'Small Elemental', 'Fire, Extraplanar', '03', 'Plane of Fire', '�', 'monstersMtoN.html#magmin', ' Damage reduction 5/magic, darkvision 60 ft., elemental traits, immunity to fire, melt weapons, vulnerability to cold'),
new Array('Manticore', 'Large Magical Beast', '', '05', 'Warm marshes', '+3 (cohort)', 'monstersMtoN.html#manticore', ' Darkvision 60 ft., low-light vision, scent'),
new Array('Medusa', 'Medium Monstrous Humanoid', '', '07', 'Temperate marshes', '�', 'monstersMtoN.html#medusa', ' Darkvision 60 ft.'),
new Array('Mephit, Air', 'Small Outsider', 'Air, Extraplanar', '03', 'Plane of Air', '+3 (cohort)', 'monstersMtoN.html#air-mephit', ' Damage reduction 5/magic, darkvision 60 ft., fast healing 2'),
new Array('Mephit, Dust', 'Small Outsider', 'Air, Extraplanar', '03', 'Plane of Air', '+3 (cohort)', 'monstersMtoN.html#dust-mephit', ' Damage reduction 5/magic, darkvision 60 ft., fast healing 2'),
new Array('Mephit, Earth', 'Small Outsider', 'Earth, Extraplanar', '03', 'Plane of Earth', '+3 (cohort)', 'monstersMtoN.html#earth-mephit', ' Change size, damage reduction 5/magic, darkvision 60 ft., fast healing 2'),
new Array('Mephit, Fire', 'Small Outsider', 'Extraplanar, Fire', '03', 'Plane of Fire', '+3 (cohort)', 'monstersMtoN.html#fire-mephit', ' Damage reduction 5/magic, darkvision 60 ft., immunity to fire, fast healing 2, vulnerability to cold'),
new Array('Mephit, Ice', 'Small Outsider', 'Air, Cold, Extraplanar', '03', 'Plane of Air', '+3 (cohort)', 'monstersMtoN.html#ice-mephit', ' Damage reduction 5/magic, darkvision 60 ft., fast healing 2, immunity to cold, vulnerability to fire'),
new Array('Mephit, Magma', 'Small Outsider', 'Fire, Extraplanar', '03', 'Plane of Fire', '+3 (cohort)', 'monstersMtoN.html#magmamephit', ' Damage reduction 5/magic, darkvision 60 ft., fast healing 2, immunity to fire, vulnerability to cold'),
new Array('Mephit, Ooze', 'Small Outsider', 'Extraplanar, Water', '03', 'Plane of Water', '+3 (cohort)', 'monstersMtoN.html#ooze-mephit', ' Damage reduction 5/magic, darkvision 60 ft., fast healing 2'),
new Array('Mephit, Salt', 'Small Outsider', 'Earth, Extraplanar', '03', 'Plane of Earth', '+3 (cohort)', 'monstersMtoN.html#salt-mephit', ' Damage reduction 5/magic, darkvision 60 ft., fast healing 2'),
new Array('Mephit, Steam', 'Small Outsider', 'Extraplanar, Fire', '03', 'Plane of Fire', '+3 (cohort)', 'monstersMtoN.html#steam-mephit', ' Damage reduction 5/magic, darkvision 60 ft., fast healing 2, immunity to fire, vulnerability to cold'),
new Array('Mephit, Water', 'Small Outsider', 'Extraplanar, Water', '03', 'Plane of Water', '+3 (cohort)', 'monstersMtoN.html#water-mephit', ' Damage reduction 5/magic, darkvision 60 ft., fast healing 2'),
new Array('Merfolk', 'Medium Humanoid', 'Aquatic', '1/2', 'Temperate aquatic', '+1', 'monstersMtoN.html#merfolk', ' Amphibious, low-light vision'),
new Array('Mimic', 'Large Aberration', 'Shapechanger', '04', 'Underground', '�', 'monstersMtoN.html#mimic', ' Darkvision 60 ft., immunity to acid, mimic shape'),
new Array('Minotaur', 'Large Monstrous Humanoid', '', '04', 'Underground', '+2', 'monstersMtoN.html#minotaur', ' Darkvision 60 ft., natural cunning, scent'),
new Array('Mohrg', 'Medium Undead', '', '08', 'Any', '�', 'monstersMtoN.html#mohrg', ' Darkvision 60 ft., undead traits'),
new Array('Mummy', 'Medium Undead', '', '05', 'Any', '�', 'monstersMtoN.html#mummy', ' Damage reduction 5/�, darkvision 60 ft., undead traits, vulnerability to fire'),
new Array('Naga, Dark', 'Large Aberration', '', '08', 'Temperate hills', '�', 'monstersMtoN.html#dark-naga', ' Darkvision 60 ft., detect thoughts, guarded thoughts, immunity to poison, resistance to charm'),
new Array('Naga, Guardian', 'Large Aberration', '', '10', 'Temperate plains', '�', 'monstersMtoN.html#guardian-naga', ' Darkvision 60 ft.'),
new Array('Naga, Spirit', 'Large Aberration', '', '09', 'Temperate marshes', '�', 'monstersMtoN.html#spirit-naga', ' Darkvision 60 ft.'),
new Array('Naga, Water', 'Large Aberration', 'Aquatic', '07', 'Temperate aquatic', '�', 'monstersMtoN.html#water-naga', ' Darkvision 60 ft.'),
new Array('Night Hag', 'Medium Outsider', 'Evil, Extraplanar', '09', 'Evil Plane', '�', 'monstersMtoN.html#night-hag', ' Damage reduction 10/cold iron and magic, immunity to fire, cold, charm, sleep, and fear, spell resistance 25'),
new Array('Nightcrawler', 'Gargantuan Undead', 'Extraplanar', '18', 'Plane of Shadow', '�', 'monstersMtoN.html#nightcrawler', ' Aversion to daylight, damage reduction 15/silver and magic, darkvision 60 ft., immunity to cold, spell resistance 31, telepathy 100 ft, tremorsense 60 ft., undead traits'),
new Array('Nightmare', 'Large Outsider', 'Evil, Extraplanar', '05', 'Evil Plane', '+4 (cohort)', 'monstersMtoN.html#nightmare', ' Astral projection, darkvision 60 ft., etherealness'),
new Array('Nightwalker', 'Huge Undead', 'Extraplanar', '16', 'Plane of Shadow', '�', 'monstersMtoN.html#nightwalker', ' Aversion to daylight, damage reduction 15/silver and magic, darkvision 60 ft., immunity to cold, spell resistance 29, telepathy 100 ft., undead traits'),
new Array('Nightwing', 'Huge Undead', 'Extraplanar', '14', 'Plane of Shadow', '�', 'monstersMtoN.html#nightwing', ' Aversion to daylight, damage reduction 15/silver and magic, darkvision 60 ft., immunity to cold, spell resistance 27, telepathy 100 ft., undead traits'),
new Array('Nymph', 'Medium Fey', '', '07', 'Temperate forests', '+7', 'monstersMtoN.html#nymph', ' Damage reduction 10/cold iron, low-light vision, unearthly grace, wild empathy'),
new Array('Ogre', 'Large Giant', '', '03', 'Temperate hills', '+2', 'monstersOtoR.html#ogre', ' Darkvision 60 ft., low-light vision'),
new Array('Ogre Mage', 'Large Giant', '', '08', 'Cold hills', '+7', 'monstersOtoR.html#ogre-mage', ' Darkvision 90 ft., low-light vision, regeneration 5, spell resistance 19'),
new Array('Ooze, Black Pudding', 'Huge Ooze', '', '07', 'Underground', '�', 'monstersOtoR.html#black-pudding', ' Blindsight 60 ft., split, ooze traits'),
new Array('Ooze, Gelatinous Cube', 'Huge Ooze', '', '03', 'Underground', '�', 'monstersOtoR.html#gelatinous-cube', ' Blindsight 60 ft., immunity to electricity, ooze traits, transparent'),
new Array('Ooze, Gray', 'Medium Ooze', '', '04', 'Cold marshes', '�', 'monstersOtoR.html#gray-ooze', ' Blindsight 60 ft., immunity to cold and fire, ooze traits, transparent'),
new Array('Ooze, Ochre Jelly', 'Large Ooze', '', '05', 'Temperate marshes', '�', 'monstersOtoR.html#ochre-jelly', ' Blindsight 60 ft., split, ooze traits'),
new Array('Orc', 'Medium Humanoid', 'Orc', '1/2', 'Temperate hills', '+0', 'monstersOtoR.html#orc', ' Darkvision 60 ft., light sensitivity'),
new Array('Otyugh', 'Large Aberration', '', '04', 'Underground', '�', 'monstersOtoR.html#otyugh', ' Darkvision 60 ft., scent'),
new Array('Owl, Giant', 'Large Magical Beast', '', '03', 'Temperate forests', '+2 (cohort)', 'monstersOtoR.html#owl-giant', ' Superior lowlight vision'),
new Array('Owlbear', 'Large Magical Beast', '', '04', 'Temperate forests', '�', 'monstersOtoR.html#owlbear', ' Scent'),
new Array('Pegasus', 'Large Magical Beast', '', '03', 'Temperate forests', '+2 (cohort)', 'monstersOtoR.html#pegasus', ' Darkvision 60 ft., low-light vision, scent, spell-like abilities'),
new Array('Phantom Fungus', 'Medium Plant', '', '03', 'Underground', '�', 'monstersOtoR.html#phantom-fungus', ' Low-light vision, plant traits, greater invisibility'),
new Array('Phase Spider', 'Large Magical Beast', '', '05', 'Warm hills', '�', 'monstersOtoR.html#phase-spider', ' Darkvision 60 ft., ethereal jaunt, low-light vision'),
new Array('Phasm', 'Medium Aberration', 'Shapechanger', '07', 'Underground', '�', 'monstersOtoR.html#phasm', ' Alternate form, amorphous, resilient, scent, telepathy 100 ft., tremorsense 60 ft.'),
new Array('Planetouched, Aasimar', 'Medium Outsider', 'Native', '1/2', 'Temperate plains', '+1', 'monstersOtoR.html#aasimar', ' Darkvision 60 ft., resistance to acid 5, cold 5, and electricity 5'),
new Array('Planetouched, Tiefling', 'Medium Outsider', 'Native', '1/2', 'Temperate plains', '+1', 'monstersOtoR.html#tiefling', ' Darkvision 60 ft., resistance to cold 5, electricity 5, and fire 5'),
new Array('Pseudodragon', 'Tiny Dragon', '', '01', 'Temperate forests', '+3', 'monstersOtoR.html#pseudodragon', ' Blindsense 60 ft., darkvision 60 ft., immunity to sleep and paralysis, low-light vision, spell resistance 19, telepathy 60 ft.'),
new Array('Purple Worm', 'Gargantuan Magical Beast', '', '12', 'Underground', '�', 'monstersOtoR.html#purple-worm', ' Tremorsense 60 ft.'),
new Array('Rakshasa', 'Medium Outsider', 'Native', '10', 'Warm marshes', '+7', 'monstersOtoR.html#rakshasa', ' Change shape, damage reduction 15/Good and piercing, darkvision 60 ft., spell resistance 27'),
new Array('Rast', 'Medium Outsider', 'Extraplanar, Fire', '05', 'Plane of Fire', '�', 'monstersOtoR.html#rast', ' Darkvision 60 ft., flight, immunity to fire, vulnerability to cold'),
new Array('Ravid', 'Medium Outsider', 'Extraplanar', '05', 'Positive Energy Plane', '�', 'monstersOtoR.html#ravid', ' Darkvision 60 ft., flight, immunity to fire'),
new Array('Remorhaz', 'Huge Magical Beast', '', '07', 'Cold desert', '�', 'monstersOtoR.html#remorhaz', ' Darkvision 60 ft., heat, low-light vision, tremorsense 60 ft.'),
new Array('Roc', 'Gargantuan Animal', '', '09', 'Warm mountains', '�', 'monstersOtoR.html#roc', ' Low-light vision'),
new Array('Roper', 'Large Magical Beast', '', '12', 'Underground', '�', 'monstersOtoR.html#roper', ' Darkvision 60 ft., immunity to electricity, low-light vision, resistance to cold 10, spell resistance 30, vulnerability to fire'),
new Array('Rust Monster', 'Medium Aberration', '', '03', 'Underground', '�', 'monstersOtoR.html#rust-monster', ' Darkvision, scent'),
new Array('Salamander, Average', 'Medium Outsider', 'Extraplanar, Fire', '06', 'Plane of Fire', '+5', 'monstersS.html#salamander', ' Damage reduction 10/magic, darkvision 60 ft., immunity to fire, vulnerability to cold'),
new Array('Salamander, Flamebrother', 'Small Outsider', 'Extraplanar, Fire', '03', 'Plane of Fire', '+4', 'monstersS.html#salamander', ' Darkvision 60 ft., immunity to fire, vulnerability to cold'),
new Array('Salamander, Noble', 'Large Outsider', 'Extraplanar, Fire', '10', 'Plane of Fire', '�', 'monstersS.html#salamander', ' Damage reduction 15/magic, darkvision 60 ft., immunity to fire, vulnerability to cold'),
new Array('Satyr', 'Medium Fey', '', '02', 'Temperate forests', '+2', 'monstersS.html#satyr', ' Damage reduction 5/cold iron, low-light vision'),
new Array('Sea Cat', 'Large Magical Beast', '', '04', 'Temperate aquatic', '�', 'monstersS.html#sea-cat', ' Darkvision 60 ft., hold breath, low-light vision, scent'),
new Array('Shadow', 'Medium Undead', 'Incorporeal', '03', 'Any', '�', 'monstersS.html#shadow', ' Darkvision 60 ft., incorporeal traits, +2 turn resistance, undead traits'),
new Array('Shadow Mastiff', 'Medium Outsider', 'Extraplanar', '05', 'Plane of Shadow', '+3 (cohort)', 'monstersS.html#shadow-mastiff', ' Darkvision 60 ft., shadow blend, scent'),
new Array('Shambling Mound', 'Large Plant', '', '06', 'Temperate marshes', '+6', 'monstersS.html#shambling-mound', ' Darkvision 60 ft., immunity to electricity, low-light vision, plant traits, resistance to fire 10'),
new Array('Shield Guardian', 'Large Construct', '', '08', 'Any', '�', 'monstersS.html#shield-guardian', ' Construct traits, darkvision 60 ft., fast healing 5, find master, guard, low-light vision, shield other, spell storing'),
new Array('Shocker Lizard', 'Small Magical Beast', '', '02', 'Warm marshes', '�', 'monstersS.html#shocker-lizard', ' Darkvision 60 ft., electricity sense, immunity to electricity, low-light vision'),
new Array('Skeleton', 'Medium Undead', '', '1/2', 'Temperate plains', '�', 'monstersS.html#skeleton', ' �'),
new Array('Skum', 'Medium Aberration', 'Aquatic', '02', 'Underground', '+3', 'monstersS.html#skum', ' Darkvision 60 ft., amphibious'),
new Array('Spectre', 'Medium Undead', 'Incorporeal', '07', 'Any', '�', 'monstersS.html#spectre', ' Darkvision 60 ft., incorporeal traits, +2 turn resistance, sunlight powerlessness, undead traits, unnatural aura'),
new Array('Sphinx, Androsphinx', 'Large Magical Beast', '', '09', 'Warm deserts', '+5 (cohort)', 'monstersS.html#androsphinx', ' Darkvision 60 ft., low-light vision'),
new Array('Sphinx, Criosphinx', 'Large Magical Beast', '', '07', 'Warm deserts', '+3 (cohort)', 'monstersS.html#criosphinx', ' Darkvision 60 ft., low-light vision'),
new Array('Sphinx, Gynosphinx', 'Large Magical Beast', '', '08', 'Warm deserts', '+4 (cohort)', 'monstersS.html#gynosphinx', ' Darkvision 60 ft., low-light vision'),
new Array('Sphinx, Hieracosphinx', 'Large Magical Beast', '', '05', 'Warm deserts', '+3 (cohort)', 'monstersS.html#hieracosphinx', ' Darkvision 60 ft., lowlight vision'),
new Array('Spider Eater', 'Large Magical Beast', '', '05', 'Temperate forests', '�', 'monstersS.html#spider-eater', ' Darkvision 60 ft., freedom of movement, lowlight vision, scent'),
new Array('Sprite, Grig', 'Tiny Fey', '', '01', 'Temperate forests', '+3', 'monstersS.html#grig', ' Damage reduction 5/cold iron, low-light vision, spell resistance 17'),
new Array('Sprite, Nixie', 'Small Fey', 'Aquatic', '01', 'Temperate aquatic', '+3', 'monstersS.html#nixie', ' Amphibious, damage reduction 5/cold iron, low-light vision, spell resistance 16, water breathing, wild empathy'),
new Array('Stirge', 'Tiny Magical Beast', '', '1/2', 'Warm marshes', '�', 'monstersS.html#stirge', ' Darkvision 60 ft., low-light vision'),
new Array('Svirfneblin', 'Small Humanoid', 'Gnome', '01', 'Underground', '+3', 'monstersS.html#svirfneblin', ' Gnome traits, svirfneblin traits, spell resistance 12'),
new Array('Swarm, Bat', 'Diminuative Animal', 'Swarm', '02', 'Temperate deserts', '�', 'monstersS.html#bat-swarm', ' Blindsense 20 ft., half damage from slashing and piercing, low-light vision, swarm traits'),
new Array('Swarm, Centipede', 'Diminuative Vermin', 'Swarm', '04', 'Underground', '�', 'monstersS.html#centipede-swarm', ' Darkvision 60 ft., immune to weapon damage, swarm traits, tremorsense 30 ft., vermin traits'),
new Array('Swarm, Hellwasp', 'Diminuative Magical Beast', 'Extraplanar, Evil, Swarm', '08', 'Evil Plane', '�', 'monstersS.html#hellwasp-swarm', ' DR 10/magic, darkvision 60 ft., hive mind, immune to weapon damage, fire resist 10, low-light vision, swarm traits'),
new Array('Swarm, Locust', 'Diminuative Vermin', 'Swarm', '03', 'Temperate plains', '�', 'monstersS.html#locust-swarm', ' Darkvision 60 ft., immune to weapon damage, swarm traits, vermin traits'),
new Array('Swarm, Rat', 'Tiny Animal', 'Swarm', '02', 'Any', '�', 'monstersS.html#rat-swarm', ' Half damage from slashing and piercing, low-light vision, scent, swarm traits'),
new Array('Swarm, Spider', 'Diminuative Vermin', 'Swarm', '01', 'Warm forests', '�', 'monstersS.html#spider-swarm', ' Darkvision 60 ft., swarm traits, tremorsense 30 ft., vermin traits'),
new Array('Tarrasque', 'Colossal Magical Beast', '', '20', 'Any', '�', 'monstersTtoZ.html#tarrasque', ' Carapace, damage reduction 15/epic, immunity to fire, poison, disease, energy drain, and ability damage, regeneration 40, scent, spell resistance 32'),
new Array('Tendriculos', 'Huge Plant', '', '06', 'Temperate forests', '�', 'monstersTtoZ.html#tendriculos', ' Low-light vision, plant traits, regeneration 10'),
new Array('Thoqqua', 'Medium Elemental', 'Earth, Extraplanar, Fire', '02', 'Plane of Fire', '�', 'monstersTtoZ.html#thoqqua', ' Darkvision 60 ft., elemental traits, immunity to fire, tremorsense 60 ft., vulnerability to cold'),
new Array('Titan', 'Huge Outsider', 'Chaotic, Extraplanar', '21', 'Chaotic Good Plane', '�', 'monstersTtoZ.html#titan', ' Damage reduction 15/Lawful, darkvision 60 ft., spell resistance 32'),
new Array('Tojanida, Adult', 'Medium Outsider', 'Extraplanar, Water', '05', 'Plane of Water', '�', 'monstersTtoZ.html#tojanida', ' All-around vision, darkvision 60 ft., immunity to acid and cold, electricity 10 and fire 10'),
new Array('Tojanida, Elder', 'Large Outsider', 'Extraplanar, Water', '09', 'Plane of Water', '�', 'monstersTtoZ.html#tojanida', ' All-around vision, darkvision 60 ft., resistance to electricity 10 and fire 10 immunity to acid and cold, resistance to electricity 10 and fire 10'),
new Array('Tojanida, Juvenile', 'Small Outsider', 'Extraplanar, Water', '03', 'Plane of Water', '�', 'monstersTtoZ.html#tojanida', ' All-around vision, darkvision 60 ft., immunity to acid and cold, resistance to'),
new Array('Treant', 'Huge Plant', '', '08', 'Temperate forests', '+5', 'monstersTtoZ.html#treant', ' Damage reduction 10/slashing, low-light vision, plant traits, vulnerability to fire'),
new Array('Triton', 'Medium Outsider', 'Native, Water', '02', 'Temperate aquatic', '+2', 'monstersTtoZ.html#triton', ' Darkvision 60 ft.'),
new Array('Troglodyte', 'Medium Humanoid', 'Reptilian', '01', 'Underground', '+2', 'monstersTtoZ.html#troglodyte', ' Darkvision 90 ft.'),
new Array('Troll', 'Large Giant', '', '05', 'Cold mountains', '+5', 'monstersTtoZ.html#troll', ' Darkvision 90 ft., low-light vision, regeneration 5, scent'),
new Array('Unicorn', 'Large Magical Beast', '', '03', 'Temperate forests', '+4 (cohort)', 'monstersTtoZ.html#unicorn', ' Darkvision 60 ft., magic circle against evil, spell-like abilities, immunity to poison, charm, and compulsion, low-light vision, scent, wild empathy'),
new Array('Vampire Spawn', 'Medium Undead', '', '04', 'Any', '�', 'monstersTtoZ.html#vampire-spawn', ' +2 turn resistance, damage reduction 5/silver, darkvision 60 ft., fast healing 2, gaseous form, resistance to cold 10 and electricity 10, spider climb, undead traits'),
new Array('Vargouille', 'Small Outsider', 'Evil, Extraplanar', '02', 'Evil Plane', '�', 'monstersTtoZ.html#vargouille', ' Darkvision 60 ft.'),
new Array('Water Elemental, Elder', 'Huge Elemental', 'Water, Extraplanar', '11', 'Plane of Water', '�', 'monstersTtoZ.html#water-elemental', ' Damage reduction 10/�, darkvision 60 ft., elemental traits'),
new Array('Water Elemental, Greater', 'Huge Elemental', 'Water, Extraplanar', '09', 'Plane of Water', '�', 'monstersTtoZ.html#water-elemental', ' Damage reduction 10/�, darkvision 60 ft., elemental traits'),
new Array('Water Elemental, Huge', 'Huge Elemental', 'Water, Extraplanar', '07', 'Plane of Water', '�', 'monstersTtoZ.html#water-elemental', ' Damage reduction 5/�, darkvision 60 ft., elemental traits'),
new Array('Water Elemental, Large', 'Large Elemental', 'Water, Extraplanar', '05', 'Plane of Water', '�', 'monstersTtoZ.html#water-elemental', ' Damage reduction 5/�, darkvision 60 ft., elemental traits'),
new Array('Water Elemental, Medium', 'Medium Elemental', 'Water, Extraplanar', '03', 'Plane of Water', '�', 'monstersTtoZ.html#water-elemental', ' Darkvision 60 ft., elemental traits'),
new Array('Water Elemental, Small', 'Small Elemental', 'Water, Extraplanar', '01', 'Plane of Water', '�', 'monstersTtoZ.html#water-elemental', ' Darkvision 60 ft., elemental traits'),
new Array('Werebear', 'Large Humanoid', 'Human, Shapechanger', '05', 'Cold forests', '+3', 'monstersKtoL.html#werebear', ' Alternate form, bear empathy, damage reduction 10/silver, low-light vision, scent'),
new Array('Wereboar', 'Medium Humanoid', 'Human, Shapechanger', '04', 'Temperate forests', '+3', 'monstersKtoL.html#wereboar', ' Alternate form, boar empathy, damage reduction 10/silver, ferocity, low-light vision, scent'),
new Array('Wererat', 'Medium Humanoid', 'Human, Shapechanger', '02', 'Any', '+3', 'monstersKtoL.html#wererat', ' Alternate form, rat empathy, damage reduction 10/silver, low-light vision, scent'),
new Array('Weretiger', 'Large Humanoid', 'Human, Shapechanger', '05', 'Warm forests', '+3', 'monstersKtoL.html#weretiger', ' Alternate form, tiger empathy, damage reduction 10/silver, low-light vision, scent'),
new Array('Werewolf', 'Medium Humanoid', 'Human, Shapechanger', '03', 'Temperate forests', '+3', 'monstersKtoL.html#werewolf', ' Alternate form, wolf empathy, damage reduction 10/silver, low-light vision, scent'),
new Array('Wight', 'Medium Undead', '', '03', 'Any', '�', 'monstersTtoZ.html#wight', ' Darkvision 60 ft., undead traits'),
new Array('Will-O�-Wisp', 'Small Aberration', 'Air', '06', 'Temperate marshes', '�', 'monstersTtoZ.html#will-o-wisp', ' Darkvision 60 ft., immunity to magic, natural invisibility'),
new Array('Winter Wolf', 'Large Magical Beast', 'Cold', '05', 'Cold forests', '+3 (cohort)', 'monstersTtoZ.html#winter-wolf', ' Darkvision 60 ft., immunity to cold, low-light vision, scent, vulnerability to fire'),
new Array('Worg', 'Medium Magical Beast', '', '02', 'Temperate plains', '+1 (cohort)', 'monstersTtoZ.html#worg', ' Darkvision 60 ft., low-light vision, scent'),
new Array('Wraith', 'Medium Undead', 'Incorporeal', '05', 'Any', '�', 'monstersTtoZ.html#wraith', ' Darkvision 60 ft., daylight powerlessness, incorporeal traits, +2 turn resistance, undead traits, unnatural aura'),
new Array('Wraith, Dread', 'Large Undead', 'Incorporeal', '11', 'Any', '�', 'monstersTtoZ.html#wraith', ' Darkvision 60 ft., daylight powerlessness, incorporeal traits, lifesense 60 ft., undead traits, unnatural aura'),
new Array('Wyvern', 'Large Dragon', '', '06', 'Warm hills', '�', 'monstersTtoZ.html#wyvern', ' Darkvision 60 ft., immunity to sleep and paralysis, low-light vision, scent'),
new Array('Xill', 'Medium Outsider', 'Extraplanar', '06', 'Ethereal Plane', '+4', 'monstersTtoZ.html#xill', ' Darkvision 60 ft., planewalk, spell resistance 21'),
new Array('Xorn, Average', 'Medium Outsider', 'Extraplanar, Earth', '06', 'Plane of Earth', '�', 'monstersTtoZ.html#xorn', ' All-around vision, earth glide, damage reduction 5/bludgeoning, darkvision 60 ft., immunity to cold and fire, resistance to electricity 10, tremorsense 60 ft.'),
new Array('Xorn, Elder', 'Large Outsider', 'Extraplanar, Earth', '08', 'Plane of Earth', '�', 'monstersTtoZ.html#xorn', ' All-around vision, earth glide, damage reduction 5/bludgeoning, darkvision 60 ft., immunity to cold and fire, resistance to electricity 10, tremorsense 60 ft.'),
new Array('Xorn, Minor', 'Small Outsider', 'Extraplanar, Earth', '03', 'Plane of Earth', '�', 'monstersTtoZ.html#xorn', ' All-around vision, earth glide, damage reduction 5/bludgeoning, darkvision 60 ft., immunity to cold and fire, resistance to electricity 10, tremorsense 60 ft.'),
new Array('Yeth Hound', 'Medium Outsider', 'Extraplanar, Evil', '03', 'Evil Plane', '+3 (cohort)', 'monstersTtoZ.html#yeth-hound', ' Damage reduction 10/silver, darkvision 60 ft., flight, scent'),
new Array('Yrthak', 'Huge Magical Beast', '', '09', 'Temperate mountains', '�', 'monstersTtoZ.html#yrthak', ' Blindsight 120 ft., immunities, vulnerability to sonic'),
new Array('Zombie', 'Medium Undead', '', '1/2', 'Any', '�', 'monstersTtoZ.html#zombie', ' Single actions only, damage reduction 5/slashing, darkvision 60 ft., undead traits'),
new Array('Devil, Imp', 'Tiny Outsider', 'Evil, Extraplanar, Lawful', '02', 'Lawful Evil Plane', '� (Improved Familiar)', 'monstersDtoDe.html#imp-devil', ' Alternate form, damage reduction 5/Good or silver, darkvision 60 ft., fast healing 2, immunity to poison, resistance to fire 5'),
new Array('Sahuagin', 'Medium Monstrous Humanoid', 'Aquatic', '02', 'Warm aquatic', '+2 (+3 if four-armed)', 'monstersS.html#sahuagin', ' Blindsense 30 ft., darkvision 60 ft., freshwater sensitivity, light blindness, speak with sharks, water dependent'),
new Array('Sprite, Pixie', 'Small Fey', '', '04', 'Temperate forests', '+4 (+6 with irresistible dance)', 'monstersS.html#pixie', ' Damage reduction 10/cold iron, greater invisibility, low-light vision, spell resistance 15')
);
